In [1]:
# """
# Vorbereitung

# 1) mit Excel Station finden, die nahe liegt  C:\Users\CasparGross\Documents\Wetterdaten für Rasmus
# 2) Wetterdaten herungerladen:
# https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/solar/
# - Solar und air_temperature

# step 1) erstmal Dateien extrahieren
# step 2) manuell in VS txt-format in csv umwandeln (einfach mit rechtsklick + rename)

# 3) Input Dateien in nächster Zeile auswählen/angeben

# 4) Metadaten in den CSV-Dateien anpassen (aus letzte Zelle) !!! hier sehr aufpassen, dass man richtige Metadaten übernimmt!!!


# Anmerkungen zu dfs:

# """

In [2]:

import pandas as pd
import numpy as np

# Inputs und Auswahl des Jahres
name = 'produkt_st_stunde_19800101_20251031_04466_Schleswig.csv'
name_tamb = 'produkt_tu_stunde_19510101_20241231_04466_Schleswig.csv'


stationsID = 'station_04466_Schleswig_neu_'
timestep = '1h_'

# # welches Jahr soll gefiltert werden?
# 2024
start = pd.Timestamp('2024-01-01 00:00')
ende = pd.Timestamp('2024-12-31 23:50')

# # 2004
# start = pd.Timestamp('2004-01-01 00:00')
# ende = pd.Timestamp('2004-12-31 23:50')


# CSV-Datei laden
df = pd.read_csv(name,sep=';')
df_Tamb = pd.read_csv(name_tamb,sep=';')
df

,STATIONS_ID,MESS_DATUM,QN_592,ATMO_LBERG,FD_LBERG,FG_LBERG,SD_LBERG,ZENIT,MESS_DATUM_WOZ,eor
0,4466,1980010100:24,1,-999.0,0.0,0.0,0,148.06,1980010101:00,eor
1,4466,1980010101:24,1,-999.0,0.0,0.0,0,144.34,1980010102:00,eor
2,4466,1980010102:24,1,-999.0,0.0,0.0,0,137.97,1980010103:00,eor
3,4466,1980010103:24,1,-999.0,0.0,0.0,0,130.10,1980010104:00,eor
4,4466,1980010104:24,1,-999.0,0.0,0.0,0,121.56,1980010105:00,eor
...,...,...,...,...,...,...,...,...,...,...
401059,4466,2025103119:05,1,116.0,0.0,0.0,0,114.66,2025103120:00,eor
401060,4466,2025103120:05,1,122.0,0.0,0.0,0,122.99,2025103121:00,eor
401061,4466,2025103121:05,1,119.0,0.0,0.0,0,130.42,2025103122:00,eor
401062,4466,2025103122:05,1,114.0,0.0,0.0,0,136.21,2025103123:00,eor
401063,4466,2025103123:05,1,105.0,0.0,0.0,0,139.47,2025110100:00,eor

In [3]:
# hier muss aufgepasst werden: manche Dateien haben %Y%m%d%H%M als Format, andere haben %Y%m%d%H:%M
df_neu = df

df_neu['MESS_DATUM'] = pd.to_datetime(df['MESS_DATUM'], format  ='%Y%m%d%H:%M') # hier muss aufgepasst werden: manche Dateien haben %Y%m%d%H%M als Format, andere haben %Y%m%d%H:%M
df_neu

df_neu_tamb = df_Tamb
df_neu_tamb['MESS_DATUM'] = pd.to_datetime(df_Tamb['MESS_DATUM'], format='%Y%m%d%H')

df_neu

,STATIONS_ID,MESS_DATUM,QN_592,ATMO_LBERG,FD_LBERG,FG_LBERG,SD_LBERG,ZENIT,MESS_DATUM_WOZ,eor
0,4466,1980-01-01 00:24:00,1,-999.0,0.0,0.0,0,148.06,1980010101:00,eor
1,4466,1980-01-01 01:24:00,1,-999.0,0.0,0.0,0,144.34,1980010102:00,eor
2,4466,1980-01-01 02:24:00,1,-999.0,0.0,0.0,0,137.97,1980010103:00,eor
3,4466,1980-01-01 03:24:00,1,-999.0,0.0,0.0,0,130.10,1980010104:00,eor
4,4466,1980-01-01 04:24:00,1,-999.0,0.0,0.0,0,121.56,1980010105:00,eor
...,...,...,...,...,...,...,...,...,...,...
401059,4466,2025-10-31 19:05:00,1,116.0,0.0,0.0,0,114.66,2025103120:00,eor
401060,4466,2025-10-31 20:05:00,1,122.0,0.0,0.0,0,122.99,2025103121:00,eor
401061,4466,2025-10-31 21:05:00,1,119.0,0.0,0.0,0,130.42,2025103122:00,eor
401062,4466,2025-10-31 22:05:00,1,114.0,0.0,0.0,0,136.21,2025103123:00,eor
401063,4466,2025-10-31 23:05:00,1,105.0,0.0,0.0,0,139.47,2025110100:00,eor

In [4]:
# Filtere den DataFrame im gewünschten Zeitraum
df_neu = df_neu[(df_neu['MESS_DATUM'] >= start) & (df_neu['MESS_DATUM'] <= ende)].reset_index(drop=True) 
df_neu_tamb = df_neu_tamb[(df_neu_tamb['MESS_DATUM'] >= start) & (df_neu_tamb['MESS_DATUM'] <= ende)].reset_index(drop=True)

df_neu

,STATIONS_ID,MESS_DATUM,QN_592,ATMO_LBERG,FD_LBERG,FG_LBERG,SD_LBERG,ZENIT,MESS_DATUM_WOZ,eor
0,4466,2024-01-01 00:24:00,1,118.0,0.0,0.0,0,148.03,2024010101:00,eor
1,4466,2024-01-01 01:24:00,1,120.0,0.0,0.0,0,144.32,2024010102:00,eor
2,4466,2024-01-01 02:24:00,1,119.0,0.0,0.0,0,137.95,2024010103:00,eor
3,4466,2024-01-01 03:24:00,1,120.0,0.0,0.0,0,130.09,2024010104:00,eor
4,4466,2024-01-01 04:24:00,1,119.0,0.0,0.0,0,121.55,2024010105:00,eor
...,...,...,...,...,...,...,...,...,...,...
8779,4466,2024-12-31 19:25:00,1,120.0,0.0,0.0,0,121.52,2024123120:00,eor
8780,4466,2024-12-31 20:25:00,1,120.0,0.0,0.0,0,130.05,2024123121:00,eor
8781,4466,2024-12-31 21:25:00,1,121.0,0.0,0.0,0,137.91,2024123122:00,eor
8782,4466,2024-12-31 22:25:00,1,121.0,0.0,0.0,0,144.27,2024123123:00,eor
8783,4466,2024-12-31 23:25:00,1,123.0,0.0,0.0,0,147.98,2025010100:00,eor

In [5]:

def timeshift_UTC_to_WOZ(messdaten):
    '''
    description:
    funktioniert für Zeitreihen mit beliebiger länge
    verschiebt die Zeitreihe im pd-df-Format von UTC auf WOZ Zeit
    checkout https://www.pveducation.org/pvcdrom/properties-of-sunlight/solar-time for equation explenation (I used Equation of Time (EoT) for timeshift_UTC_to_WOZ )

    input:
    pd df mit Spalte 'MESS_DATUM'
    output:
    gibt Spalte mit korrigierten Zeitstempeln zurück
    '''

    # initialisieren der np arrays --> kann später auch gekürzt werden, wenn eh Schleife genutzt wird, müssen einzelne Werte nicht gespeichert werden
    # B = np.zeros(len(messdaten))
    # timeshift_UTC_to_WOZ = np.zeros(len(messdaten))
    WOZ = messdaten['MESS_DATUM']

    for i in range(len(messdaten)):  
        # hier wird Formel für shift von UTC zu WOZ umgesetzt --> der WOZ-df hat als Messzeitpunkt Einträge immer die Zeitlichen Einträge, verschoben um die Korrektur, die sich aus der oben visualisierten Kurve ergibt
        
        today = messdaten['MESS_DATUM'][i]
        d = today - start 
        d = d.days
        B = 360/365*(d - 81)
        timeshift_UTC_to_WOZ = round(9.87* np.sin(  np.deg2rad(2*B)  ) -   7.53 * np.cos(  np.deg2rad(B)  )  - 1.5 * np.sin( np.deg2rad(B) ))
        WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
    return(WOZ)


WOZ = timeshift_UTC_to_WOZ(df_neu)
WOZ

# hier sieht man, warum man keine for schleife benutzen sollte... das dauert einfach ewig

C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WOZ[i] = today + pd.to_timedelta(timeshift_UTC_to_WOZ, unit='m')
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\3311359829.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

0      2024-01-01 00:21:00
1      2024-01-01 01:21:00
2      2024-01-01 02:21:00
3      2024-01-01 03:21:00
4      2024-01-01 04:21:00
               ...
8779   2024-12-31 19:22:00
8780   2024-12-31 20:22:00
8781   2024-12-31 21:22:00
8782   2024-12-31 22:22:00
8783   2024-12-31 23:22:00
Name: MESS_DATUM, Length: 8784, dtype: datetime64[ns]

In [6]:
#Transition von J/cm^2 [DWD] zu W/m^2 [PVSyst]
# 
# 1W = 1J/s 
# 1m^2 = 100^2 cm^2
# alle Werte sind in 15 Minuten Schritten
# --> 1 J/cm^2 = 100^2[Fläche]/(60[s->min]*15[timestep]*) W/m^2

# energy_to_power_15min = (100^2)/(60*15) # J/cm^2 to W/m^2 [15min]
energy_to_power_1h    = (100**2)/(60**2) # J/cm^2 to W/m^2 [1h] # später addiere ich ja werte und teile sie durch 4 --> braucht nur einen Transition Faktor

In [7]:
df_neu_relevant = df_neu[['MESS_DATUM']]

# hier  auf WOZ-Timestamps wechseln und in Format von PV-Sys speichern (für alles eigene Spalten)

df_neu_relevant['Year'] = WOZ.dt.year
df_neu_relevant['Month'] = WOZ.dt.month
df_neu_relevant['Day'] = WOZ.dt.day
df_neu_relevant['Hour'] = WOZ.dt.hour
df_neu_relevant['Minute'] = WOZ.dt.minute

df_neu_relevant['GHI'] = df_neu['FG_LBERG'] * energy_to_power_1h
df_neu_relevant['DHI'] = df_neu['FD_LBERG'] * energy_to_power_1h
# Temperatur hinzufügen
df_neu_relevant['Tamb'] = df_neu_tamb['TT_TU']

# da ich aus 1h Werten 1h Werte mache, brauche ich hier keine weiteren Berechnungen (nur Timeshift von oben)


df_neu_relevant.drop(columns=['MESS_DATUM'], inplace=True)

df_neu_relevant

#   -->  Ziel Format: ;;;;;W/m2;W/m2;deg.C

C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\1254683425.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_neu_relevant['Year'] = WOZ.dt.year
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\1254683425.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_neu_relevant['Month'] = WOZ.dt.month
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\1254683425.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_neu_relevant['Day'] = WOZ.dt.day
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\1254683425.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_neu_relevant['Hour'] = WOZ.dt.hour
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\1254683425.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_neu_relevant['Minute'] = WOZ.dt.minute
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\1254683425.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_neu_relevant['GHI'] = df_neu['FG_LBERG'] * energy_to_power_1h
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\1254683425.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_neu_relevant['DHI'] = df_neu['FD_LBERG'] * energy_to_power_1h
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\1254683425.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_neu_relevant['Tamb'] = df_neu_tamb['TT_TU']
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_32164\1254683425.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_neu_relevant.drop(columns=['MESS_DATUM'], inplace=True)

      Year  Month  Day  Hour  Minute  GHI  DHI  Tamb
0     2024      1    1     0      21  0.0  0.0   6.9
1     2024      1    1     1      21  0.0  0.0   6.9
2     2024      1    1     2      21  0.0  0.0   6.6
3     2024      1    1     3      21  0.0  0.0   6.5
4     2024      1    1     4      21  0.0  0.0   6.5
...    ...    ...  ...   ...     ...  ...  ...   ...
8779  2024     12   31    19      22  0.0  0.0   4.1
8780  2024     12   31    20      22  0.0  0.0   4.5
8781  2024     12   31    21      22  0.0  0.0   5.0
8782  2024     12   31    22      22  0.0  0.0   5.3
8783  2024     12   31    23      22  0.0  0.0   5.1

[8784 rows x 8 columns]

In [8]:

new_row = ['', '', '', '', '','W/m2','W/m2','deg.C']   

# einheiten einfügen bei CSV -> entkommentieren der beiden Zeilen unten
# #df_15 = pd.concat([pd.DataFrame([new_row], columns=df_15.columns), df_15], ignore_index=True) # nur einmal einfügen
# Einheiten-Spalte nur einmal einfügen:
df_neu_relevant = pd.concat([pd.DataFrame([new_row], columns=df_neu_relevant.columns), df_neu_relevant], ignore_index=True) 


df_neu_relevant

      Year Month Day Hour Minute   GHI   DHI   Tamb
0                                 W/m2  W/m2  deg.C
1     2024     1   1    0     21   0.0   0.0    6.9
2     2024     1   1    1     21   0.0   0.0    6.9
3     2024     1   1    2     21   0.0   0.0    6.6
4     2024     1   1    3     21   0.0   0.0    6.5
...    ...   ...  ..  ...    ...   ...   ...    ...
8780  2024    12  31   19     22   0.0   0.0    4.1
8781  2024    12  31   20     22   0.0   0.0    4.5
8782  2024    12  31   21     22   0.0   0.0    5.0
8783  2024    12  31   22     22   0.0   0.0    5.3
8784  2024    12  31   23     22   0.0   0.0    5.1

[8785 rows x 8 columns]

In [9]:
#achtung! name muss noch im cache sein!

# name_new_1 = name.replace('.csv', '_2024_1h_1_for_pv_syst.csv')
from ntpath import join


start_string = start.strftime("%Y-%m-%d")
ende_string = ende.strftime("%Y-%m-%d") 

csv_eding = 'for_pv_syst.csv'
name_new_1 = ''.join([stationsID,start_string,ende_string,timestep,'_1_',csv_eding])

# nur ausführen wenn Datei ready ist, sonst wird bestehende Datei überschrieben 
df_neu_relevant.to_csv(name_new_1, sep=';', index=False, header=['Year','Month','Day','Hour','Minute','GHI','DHI','Tamb'])


#   diese Header händisch hinzufügen

#Meteo hourly data;;;;;;;
#Description of Data Set e.g. DWD DataBase;;;;;;;
# GHI. DHI and Temp are retrieved. Set Time Zone to 0. since time stamp is in UTC!;;;;;;;
#Site; 03987_Potsdam;;;;;;;
#Country; germany;;;;;;;
#Data Source; DWD_station_03987;;;;;;;
#Time step; 1h;;;;;;;
#Year; 2024;;;;;;;
#Latitude; 52.3812;;;;;;;
#Longitude; 13.0622;;;;;;;
#Altitude; 81;;;;;;;
#Time Zone; 1  ;;;;;;;
#Time reference;UT;;;;;;
#Hour Shift;-1;;;;;;
#Time Shift;0;;;;;;

# --> muss aber individuell je nach Metadaten angepasst werden (könnte man aber in Zukunft automatisieren)

# Zielformat
# Year;Month;Day;Hour;Minute;GHI;Tamb;
# ;;;;;W/m2;deg.C;

In [10]:
"""
ToDo:

# location checken
# Windgeschwindigkeit u Temp ergänzen --> müsste aus Metadaten hervorgehen, wo die zu finden sind.

# Simulieren mit Lima

# in Zukunft Interpolieren, wenn Werte fehlen!!! -> hat jetzt durch Zufall auch ohne funktioniert, aber kann man sich nicht 100%ig drauf verlassen

# Wetterstationen filtern später

UTF-Zeitformat anpassen --> bisher ist noch nicht der Switch zwischen UTF + 1 und local Time integriert
wenn ich das aber richtig aus dr Doku lese, dann reicht es am Anfang #Time Reference; 1  zu ergänzen --> das müsste für PV-Syst dann klar stellen, dass es selbst den Shift von UTF 1 zu local time macht

https://www.pvsyst.com/help/meteo-database/notes-on-meteo/meteonote7-time-shift-in-meteo-files.html#time-shift-correction-when-importing-data 
If there is a time shift varying along the year:

With the general ASCII importing tool, consider using the DST correction (option "Summer Time > Apply").
Otherwise there is no practical way, except modifying the dates directly in the source file.
If the file is written in UT (Universal Time):

With the general ASCII importing tool, check the box "Universal time".
With PVsyst standard format, you can add a line #Time Reference with the value UT

"""

'\nToDo:\n\n# location checken\n# Windgeschwindigkeit u Temp ergänzen --> müsste aus Metadaten hervorgehen, wo die zu finden sind.\n\n# Simulieren mit Lima\n\n# in Zukunft Interpolieren, wenn Werte fehlen!!! -> hat jetzt durch Zufall auch ohne funktioniert, aber kann man sich nicht 100%ig drauf verlassen\n\n# Wetterstationen filtern später\n\nUTF-Zeitformat anpassen --> bisher ist noch nicht der Switch zwischen UTF + 1 und local Time integriert\nwenn ich das aber richtig aus dr Doku lese, dann reicht es am Anfang #Time Reference; 1  zu ergänzen --> das müsste für PV-Syst dann klar stellen, dass es selbst den Shift von UTF 1 zu local time macht\n\nhttps://www.pvsyst.com/help/meteo-database/notes-on-meteo/meteonote7-time-shift-in-meteo-files.html#time-shift-correction-when-importing-data \nIf there is a time shift varying along the year:\n\nWith the general ASCII importing tool, consider using the DST correction (option "Summer Time > Apply").\nOtherwise there is no practical way, except modifying the dates directly in the source file.\nIf the file is written in UT (Universal Time):\n\nWith the general ASCII importing tool, check the box "Universal time".\nWith PVsyst standard format, you can add a line #Time Reference with the value UT\n\n'