In [1]:
# """
# Vorbereitung

# 1) mit Excel Station finden, die nahe liegt  C:\Users\CasparGross\Documents\Wetterdaten für Rasmus
# 2) Wetterdaten herungerladen:
# https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/solar/
# - Solar und air_temperature

# step 1) erstmal Dateien extrahieren
# step 2) manuell in VS txt-format in csv umwandeln (einfach mit rechtsklick + rename)

# 3) Input Dateien in nächster Zeile auswählen/angeben

# 4) Metadaten in den CSV-Dateien anpassen (aus letzte Zelle) !!! hier sehr aufpassen, dass man richtige Metadaten übernimmt!!!


# Anmerkungen zu dfs:

# """

In [2]:
# hier Koordinaten von zu untersuchendem Standort eintragen: !!!mit . asl dezimalstelle!!!
long_kraftwerk, lat_kraftwerk = 13.4050, 52.5200  # Berlin
long_kraftwerk, lat_kraftwerk = 14.9506 , 51.1621  # Görlitz




# # welches Jahr soll gefiltert werden?

# 2025
year = "20251231"
datenval = "2025_Datenvalidierung"




# #  könnte man schon hier als Input nehmen:
# #  start = pd.Timestamp('2025-01-01 00:00')
# # ende = pd.Timestamp('2025-12-31 23:50')


# # 2024
# year = "20241231"


# # 2004
# year = "20041231"

In [ ]:
import pandas as pd
import numpy as np
name_stations_excel = r"C:\Users\CasparGross\Documents\Wetterdaten für Rasmus\Stationen_1h_incl_2025.csv"

path_to_downloaded_zips = r"C:\Users\CasparGross\KRAFTWERK RPS GmbH\01 - CC\01_CC_NEU\04_CC_PLANNING&IMPLEMENTATION\03_YIELD\01_GHI-DATA_spec\DWD_observations_germany_hourly_20260216.zip\DWD_observations_germany_hourly_20260216/solar/"

# CSV-Datei laden
stationen_1h_meta = pd.read_csv(name_stations_excel,sep=';',decimal=',', skiprows=2)
stationen_1h_meta



# indicees_= np.array([i for i in range(len(stationen_1h_meta)-1) if  stationen_1h_meta[year][i] == 1])
indicees_= np.array([i for i in range(len(stationen_1h_meta)-1) if  stationen_1h_meta[year][i] == 1 and stationen_1h_meta[datenval][i] != -1])
# indicees_
#stationen_mit_daten = stationen_1h_meta(indicees_)
# stationen_mit_daten

# hier einmal den df für 1h erstellen, indem wir die Einträge der vollen Stunde übernehmen.
stationen_mit_daten = stationen_1h_meta.iloc[indicees_].reset_index(drop=True)  
stationen_mit_daten

,ID,Start,Ende,NR,lat,long,Ort,Bundesland,Unnamed: 8,Ende.1,20251231,2025_Datenvalidierung,20241231,2024_Datenvalidierung,20041231,2004_Datenvalidierung,Unnamed: 16
0,183.0,19810101.0,20251231.0,42.0,54.6791,13.4344,Arkona,Mecklenburg-Vorpommern,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
1,662.0,19580101.0,20251231.0,81.0,52.2915,10.4464,Braunschweig,Niedersachsen,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
2,691.0,20090101.0,20251231.0,4.0,53.0451,8.7981,Bremen,Bremen,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN
3,853.0,19810101.0,20251231.0,416.0,50.7913,12.8720,Chemnitz,Sachsen,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
4,867.0,20210101.0,20251231.0,344.0,50.3066,10.9679,Lautertal-Oberlauter,Bayern,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN
5,1048.0,19960901.0,20251231.0,228.0,51.1278,13.7543,Dresden-Klotzsche,Sachsen,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
6,1346.0,20230101.0,20251231.0,1486.0,47.8748,8.0038,Feldberg/Schwarzwald,Baden-WÃ¼rttemberg,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN
7,1358.0,19580101.0,20251231.0,1213.0,50.4283,12.9536,Fichtelberg,Sachsen,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
8,1639.0,20240101.0,20251231.0,203.0,50.6017,8.6439,GieÃŸen/Wettenberg,Hessen,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,NaN
9,1684.0,20010101.0,20251231.0,239.0,51.1621,14.9506,GÃ¶rlitz,Sachsen,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
10,1975.0,20050101.0,20251231.0,11.0,53.6332,9.9881,Hamburg-FuhlsbÃ¼ttel,Hamburg,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN
11,2290.0,19530101.0,20251231.0,977.0,47.8009,11.0108,HohenpeiÃŸenberg,Bayern,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
12,2712.0,19770101.0,20251231.0,428.0,47.6952,9.1307,Konstanz,Baden-WÃ¼rttemberg,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
13,2925.0,20210101.0,20251231.0,356.0,51.3932,10.3123,Leinefelde,ThÃ¼ringen,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN
14,3015.0,19810101.0,20251231.0,98.0,52.2085,14.1180,Lindenberg,Brandenburg,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
15,3631.0,19640101.0,20251231.0,12.0,53.7123,7.1519,Norderney,Niedersachsen,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
16,3668.0,20090101.0,20251231.0,314.0,49.5030,11.0549,NÃ¼rnberg,Bayern,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN
17,3987.0,19451231.0,20251231.0,81.0,52.3812,13.0622,Potsdam,Brandenburg,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
18,4271.0,19980101.0,20251231.0,5.0,54.1803,12.0808,Rostock-WarnemÃ¼nde,Mecklenburg-Vorpommern,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
19,4336.0,19810101.0,20251231.0,319.0,49.2128,7.1077,SaarbrÃ¼cken-Ensheim,Saarland,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
20,4393.0,20080701.0,20251231.0,5.0,54.3279,8.6031,Sankt,Peter-Ording,Schleswig-Holstein,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN
21,4466.0,19800101.0,20251231.0,43.0,54.5275,9.5487,Schleswig,Schleswig-Holstein,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
22,4928.0,19790101.0,20251231.0,314.0,48.8281,9.2000,Stuttgart,(Schnarrenberg),Baden-WÃ¼rttemberg,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
23,5100.0,19580101.0,20251231.0,261.0,49.7479,6.6583,Trier-Petrisberg,Rheinland-Pfalz,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
24,5142.0,20220101.0,20251231.0,1.0,53.7445,14.0698,UeckermÃ¼nde,Mecklenburg-Vorpommern,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN
25,5404.0,19610101.0,20251231.0,477.0,48.4024,11.6946,Weihenstephan-DÃ¼rnast,Bayern,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
26,5705.0,19570101.0,20251231.0,268.0,49.7704,9.9576,WÃ¼rzburg,Bayern,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
27,5779.0,19810101.0,20251231.0,877.0,50.7313,13.7516,Zinnwald-Georgenfeld,Sachsen,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
28,5792.0,20130101.0,20251231.0,2956.0,47.4210,10.9848,Zugspitze,Bayern,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN
29,5856.0,19970102.0,20251231.0,476.0,48.5451,13.3532,FÃ¼rstenzell,Bayern,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
30,5906.0,19790101.0,20251231.0,98.0,49.5063,8.5584,Mannheim,Baden-WÃ¼rttemberg,NaN,NaN,1.0,0.0,1.0,0.0,1.0,0.0,NaN
31,6197.0,20220101.0,20251231.0,258.0,51.8664,9.2710,LÃ¼gde-Paenbruch,Nordrhein-Westfalen,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN
32,7365.0,20090101.0,20251231.0,180.0,51.4458,7.2628,Bochum,(RuhruniversitÃ¤t),Nordrhein-Westfalen,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN
33,7370.0,20210101.0,20251231.0,499.0,49.3910,12.6838,WaldmÃ¼nchen,Bayern,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN
34,15000.0,20230101.0,20251231.0,231.0,50.7983,6.0244,Aachen-Orsbach,Nordrhein-Westfalen,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN

In [11]:
stationen_mit_daten["lat"]

0     54.6791
1     52.2915
2     53.0451
3     50.7913
4     50.3066
5     51.1278
6     47.8748
7     50.4283
8     50.6017
9     51.1621
10    53.6332
11    47.8009
12    47.6952
13    51.3932
14    52.2085
15    53.7123
16    49.5030
17    52.3812
18    54.1803
19    49.2128
20    54.3279
21    54.5275
22    48.8281
23    49.7479
24    53.7445
25    48.4024
26    49.7704
27    50.7313
28    47.4210
29    48.5451
30    49.5063
31    51.8664
32    51.4458
33    49.3910
34    50.7983
Name: lat, dtype: float64

In [12]:

from pyproj import Transformer
from geographiclib.geodesic import Geodesic
import math


# def geodesic_distance_m(lat1, lon1, lat2, lon2):
#     res = Geodesic.WGS84.Inverse(lat1, lon1, lat2, lon2)
#     return res['s12']  # in meter

# d = geodesic_distance_m(52.5200, 13.4050, 48.1371, 11.5754)

def abstand_berechnen(stationen_mit_daten):
    # WGS84 (lon, lat) -> ETRS89 / UTM zone 33N (E,N in Metern)
    # transformer = Transformer.from_crs("EPSG:4326", "EPSG:25833", always_xy=True)
    
    # E       = stationen_mit_daten["lat"]
    # N       = stationen_mit_daten["lat"]
    # Dist    = stationen_mit_daten["lat"]

    # long_kraftwerk_m, lat_kraftwerk_m = transformer.transform(long_kraftwerk,lat_kraftwerk)
    # x = (long_kraftwerk_m, lat_kraftwerk_m)
    # print(x)

    # for i in range(len(stationen_mit_daten[year])-1):
    #     lat = float(stationen_mit_daten["lat"][i])
    #     long  = float(stationen_mit_daten["long"][i])
    #     # print(lat,long)
    #     E[i], N[i] = transformer.transform(long, lat)
    #     Dist[i].replace( math.dist(x,(E[i], N[i]))  )
    
    # return(Dist)
    

    Dist    = stationen_mit_daten["lat"]
    for i in range(len(stationen_mit_daten[year])):
        lat = float(stationen_mit_daten["lat"][i])
        long  = float(stationen_mit_daten["long"][i])
        #print(lat,long)
        Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
        
        #print(Dist[i] )
    return(Dist)



Dist = abstand_berechnen(stationen_mit_daten)

Dist

# stationen_mit_daten["Ort"]

C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist
C:\Users\CasparGross\AppData\Local\Temp\ipykernel_31216\987770596.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Dist[i] = Geodesic.WGS84.Inverse(lat, long, lat_kraftwerk, long_kraftwerk)['s12']  # ist ein ziemlich cooles Packet und gibt die als Output ein Dict, wo  's12' die Distanz in meter ist

0     404430.264734
1     335557.129606
2     470546.851780
3     151696.061347
4     296793.372332
5      83801.549045
6     621417.331850
7     162744.758744
8     448052.267483
9          0.000000
10    435381.326530
11    470230.282882
12    571444.181329
13    324615.522638
14    129882.902890
15    601049.813027
16    333089.724408
17    188108.854154
18    387857.650016
19    600241.630749
20    554483.736086
21    521950.639459
22    487041.527126
23    609168.899620
24    293524.869095
25    386186.552920
26    386726.917295
27     96937.175088
28    506130.789822
29    312906.648884
30    490757.498457
31    401871.586781
32    536812.556818
33    254771.761118
34    627782.264590
Name: lat, dtype: float64

In [13]:

print(stationen_mit_daten["Ort"][Dist.idxmin()])
the_chosen_one = stationen_mit_daten.iloc[[Dist.idxmin()]]
the_chosen_one

GÃ¶rlitz

,ID,Start,Ende,NR,lat,long,Ort,Bundesland,Unnamed: 8,Ende.1,20251231,2025_Datenvalidierung,20241231,2024_Datenvalidierung,20041231,2004_Datenvalidierung,Unnamed: 16
9,1684.0,20010101.0,20251231.0,239.0,0.0,14.9506,GÃ¶rlitz,Sachsen,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN

In [14]:
id_DWD_station = the_chosen_one["ID"]
id_DWD_station

9    1684.0
Name: ID, dtype: float64

ERROR: Could not find a version that satisfies the requirement zipfile (from versions: none)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for zipfile

In [20]:
path_to_downloaded_zips = r"C:\Users\CasparGross\KRAFTWERK RPS GmbH\01 - CC\01_CC_NEU\04_CC_PLANNING&IMPLEMENTATION\03_YIELD\01_GHI-DATA_spec\DWD_observations_germany_hourly_20260216.zip\DWD_observations_germany_hourly_20260216/solar/stundenwerte_ST_01684_row.zip"


import zipfile

archive = zipfile.ZipFile(path_to_downloaded_zips)
# Let us verify the operation..
txtdata = archive.read("mail.txt")
print(txtdata)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\CasparGross\\KRAFTWERK RPS GmbH\\01 - CC\\01_CC_NEU\\04_CC_PLANNING&IMPLEMENTATION\\03_YIELD\\01_GHI-DATA_spec\\DWD_observations_germany_hourly_20260216.zip\\DWD_observations_germany_hourly_20260216/solar/stundenwerte_ST_01684_row.zip'

In [ ]:
# import matplotlib.pyplot as plt


# x=stationen_mit_daten["Ort"]
# y=Dist[1].transpose

# fig, axes = plt.subplots(figsize=(8,8),nrows=2, ncols=1)
# ax1=plt.subplot(2,1,1)

# Dist[1].plot(ax=axes[0,1], kind='bar', grid=True)

# # plt.plot(x,y)

# # #ax2=plt.subplot(2,2,2)
# # df["b"].plot(ax=axes[0,1], kind='bar', grid=True)
# # df["c"].plot(ax=axes[1,0], kind='bar', grid=True)
# # df["d"].plot(ax=axes[1,1], kind='bar', grid=True)

# # ax1.grid(True)
# # ax1.set_ylabel('Test')
# # ax1.set_xlabel('Test2')

# #ax2.set_ylabel('Test')

In [ ]:

import pandas as pd
import numpy as np

# Inputs und Auswahl des Jahres
name = 'produkt_st_stunde_19580101_20251231_00662_Braunschweig.csv'
name_tamb = 'produkt_tu_stunde_20240805_20260205_00662_Braunschweig.csv'


stationsID = 'station_00662_Braunschweig'
timestep = '1h_'

# # welches Jahr soll gefiltert werden?
# 2025
start = pd.Timestamp('2025-01-01 00:00')
ende = pd.Timestamp('2025-12-31 23:50')



# # # welches Jahr soll gefiltert werden?
# # 2024
# start = pd.Timestamp('2024-01-01 00:00')
# ende = pd.Timestamp('2024-12-31 23:50')

# # 2004
# start = pd.Timestamp('2004-01-01 00:00')
# ende = pd.Timestamp('2004-12-31 23:50')


# CSV-Datei laden
df = pd.read_csv(name,sep=';')
df_Tamb = pd.read_csv(name_tamb,sep=';')
df_Tamb

       STATIONS_ID  MESS_DATUM  QN_9  TT_TU  RF_TU  eor
0              662  2024080500     3   14.1   80.0  eor
1              662  2024080501     3   13.1   88.0  eor
2              662  2024080502     3   13.7   86.0  eor
3              662  2024080503     3   14.1   86.0  eor
4              662  2024080504     3   14.4   84.0  eor
...            ...         ...   ...    ...    ...  ...
13195          662  2026020519     1   -2.1   95.0  eor
13196          662  2026020520     1   -1.9   95.0  eor
13197          662  2026020521     1   -1.6   94.0  eor
13198          662  2026020522     1   -1.2   94.0  eor
13199          662  2026020523     1   -0.9   95.0  eor

[13200 rows x 6 columns]

In [ ]:
#achtung! name muss noch im cache sein!

# name_new_1 = name.replace('.csv', '_2024_1h_1_for_pv_syst.csv')
from ntpath import join


start_string = start.strftime("%Y-%m-%d")
ende_string = ende.strftime("%Y-%m-%d") 

csv_eding = 'for_pv_syst.csv'
name_new_1 = ''.join([stationsID,"_",start_string,"_",ende_string,"_",timestep,'_1_',csv_eding])

# nur ausführen wenn Datei ready ist, sonst wird bestehende Datei überschrieben 
df_neu_relevant.to_csv(name_new_1, sep=';', index=False, header=['Year','Month','Day','Hour','Minute','GHI','DHI','Tamb'])


#   diese Header händisch hinzufügen

#Meteo hourly data;;;;;;;
#Description of Data Set e.g. DWD DataBase;;;;;;;
# GHI. DHI and Temp are retrieved. Set Time Zone to 0. since time stamp is in UTC!;;;;;;;
#Site; 00662_Braunschweig;;;;;;;
#Country; germany;;;;;;;
#Data Source; DWD_station_00662_Braunschweig;;;;;;;
#Time step; 1h;;;;;;;
#Year; 2024;;;;;;;
#Latitude; 52.2915;;;;;;;
#Longitude; 10.4464;;;;;;;
#Altitude; 81.44;;;;;;;
#Time Zone; 1  ;;;;;;;
#Time reference;UT;;;;;;
#Hour Shift;-1;;;;;;
#Time Shift;0;;;;;;

# --> muss aber individuell je nach Metadaten angepasst werden (könnte man aber in Zukunft automatisieren)

# Zielformat
# Year;Month;Day;Hour;Minute;GHI;Tamb;
# ;;;;;W/m2;deg.C;

NameError: name 'df_neu_relevant' is not defined

In [ ]:
"""
ToDo:

# location checken

# Simulieren mit Lima

# in Zukunft Interpolieren, wenn Werte fehlen!!! -> hat jetzt durch Zufall auch ohne funktioniert, aber kann man sich nicht 100%ig drauf verlassen

# Wetterstationen filtern später


Index of /climate_environment/CDC/observations_germany/climate/hourly/solar/
https://www.pvsyst.com/help/meteo-database/notes-on-meteo/meteonote7-time-shift-in-meteo-files.html#time-shift-correction-when-importing-data 


"""

'\nToDo:\n\n# location checken\n\n# Simulieren mit Lima\n\n# in Zukunft Interpolieren, wenn Werte fehlen!!! -> hat jetzt durch Zufall auch ohne funktioniert, aber kann man sich nicht 100%ig drauf verlassen\n\n# Wetterstationen filtern später\n\n\nEs reicht am Anfang #Time Reference; 1  zu ergänzen --> das müsste für PV-Syst dann klar stellen, dass es selbst den Shift von UTF 1 zu local time macht\n\nhttps://www.pvsyst.com/help/meteo-database/notes-on-meteo/meteonote7-time-shift-in-meteo-files.html#time-shift-correction-when-importing-data \nIf there is a time shift varying along the year:\n\nWith the general ASCII importing tool, consider using the DST correction (option "Summer Time > Apply").\nOtherwise there is no practical way, except modifying the dates directly in the source file.\nIf the file is written in UT (Universal Time):\n\nWith the general ASCII importing tool, check the box "Universal time".\nWith PVsyst standard format, you can add a line #Time Reference with the value UT\n\n'